In [ ]:
""" 
1. Create Two Array Perform 1. Addition using operator 2. Addition using function
2 Create Two Array Perform 1. Subtraction using operator 2. Subtraction using function
3. Create Two Array Perform 1, Multiplication using operator 2, Muftiplication using function
4. Create Two Array Perform 1. Division using operator 2. Division using function
5. Create Two Array Perform 1. Exponentiation using operator 2. Exponentiation using
function
6. Create Two Array Perform 1. Modulus using operator 2. Modulus using function
7. Create & 1D array, Convert 1D array into a 2D array, transpose the 2D array.
8. Create an Array with datalype as float, round the array to two decimal places.
9, create a 1D array with 5 elements, calculate the median
10, create a 1D array with 6 elements, calculate the median
11 create a 2D array 
  1. compute median along horizontal axis.
  2. compute median along vertical axis
  3. compute median of entire array
12. Create a array with element as Student Marks, compute the mean of marks
11. create a 2D array 
  1. compute Mean along horizontal axis.
  2, compute Mean along vertical axis
  3. compute Mean of entire array
14. Create a array with element as Student Marks, compute the Standard Deviation of marks.
15. create a 2D array 
   1, compute Standard Deviation along horizontal axis.
   2. compute Standard Deviation along vertical axis
   3. compute Standard Deviation of entire array
16. Create an array and find minimum and maximum value of array """

In [1]:
import numpy as np

#### 1. Create Two Array Perform 
* 1. Addition using operator 
* 2. Addition using function

In [5]:
array1 = np.arange(10,20,2)
array2 = np.arange(1,10,2)
print(f"Addition of two array using operator:{array1+array2}")
print(f"Addition of two array using function:{np.add(array1,array2)}")

Addition of two array using operator:[11 15 19 23 27]
Addition of two array using function:[11 15 19 23 27]


#### 2 Create Two Array Perform 
* 1. Subtraction using operator 
* 2. Subtraction using function

In [10]:
arr1 = np.arange(100,200,5)
arr2 = np.arange(1,100,5)
print(f"Subtraction of two array using operator:\n{arr1+arr2}")
print(f"Subtraction of two array using function:{np.subtract(arr1,arr2)}")

Subtraction of two array using operator:
[101 111 121 131 141 151 161 171 181 191 201 211 221 231 241 251 261 271
 281 291]
Subtraction of two array using function:[99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99 99]


#### 3. Create Two Array Perform 
* 1, Multiplication using operator 
* 2, Muftiplication using function

In [13]:
print(f"Multiplication of two array using operator: \n{arr1*arr2}")
print(f"Multiplication of two array using function: \n{np.multiply(arr1,arr2)}")

Multiplication of two array using operator: 
[  100   630  1210  1840  2520  3250  4030  4860  5740  6670  7650  8680
  9760 10890 12070 13300 14580 15910 17290 18720]
Multiplication of two array using function: 
[  100   630  1210  1840  2520  3250  4030  4860  5740  6670  7650  8680
  9760 10890 12070 13300 14580 15910 17290 18720]


#### 4. Create Two Array Perform 
* 1. Division using operator 
* 2. Division using function

In [15]:
print(f"Divison of two array using operator: \n{arr1/arr2}")
print(f"Divison of two array using function: \n{np.divide(arr1,arr2)}")

Divison of two array using operator: 
[100.          17.5         10.           7.1875       5.71428571
   4.80769231   4.19354839   3.75         3.41463415   3.15217391
   2.94117647   2.76785714   2.62295082   2.5          2.3943662
   2.30263158   2.22222222   2.15116279   2.08791209   2.03125   ]
Divison of two array using function: 
[100.          17.5         10.           7.1875       5.71428571
   4.80769231   4.19354839   3.75         3.41463415   3.15217391
   2.94117647   2.76785714   2.62295082   2.5          2.3943662
   2.30263158   2.22222222   2.15116279   2.08791209   2.03125   ]


#### 5. Create Two Array Perform 
* 1. Exponentiation using operator 
* 2. Exponentiation using
function

In [17]:
arr3 = np.array([2,4,6,8])
arr4 = np.array([1,3,5,7])
print(f"Exponenation of two array using operator: \n{arr3**arr4}")
print(f"Exponenation of two array using function: \n{np.power(arr3,arr4)}")

Exponenation of two array using operator: 
[      2      64    7776 2097152]
Exponenation of two array using function: 
[      2      64    7776 2097152]


#### 6. Create Two Array Perform 
* 1. Modulus using operator 
* 2. Modulus using function

In [18]:
print(f"Exponenation of two array using operator: \n{arr3%arr4}")
print(f"Exponenation of two array using function: \n{np.mod(arr3,arr4)}")

Exponenation of two array using operator: 
[0 1 1 1]
Exponenation of two array using function: 
[0 1 1 1]


#### 7. Create & 1D array, Convert 1D array into a 2D array, transpose the 2D array.

In [23]:
arr5 = np.arange(1,25,2)
print(f"1D Array:{arr5}")

convert_into_2d = np.reshape(arr5,(3,4))
print(f"Convert into 2D Array: \n {convert_into_2d}")

tranpose_2d = np.transpose(convert_into_2d)
print(f"Transpose 2D Array: \n {tranpose_2d}")

1D Array:[ 1  3  5  7  9 11 13 15 17 19 21 23]
Convert into 2D Array: 
 [[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]]
Transpose 2D Array: 
 [[ 1  9 17]
 [ 3 11 19]
 [ 5 13 21]
 [ 7 15 23]]


#### 8. Create an Array with datatype as float, round the array to two decimal places.

In [30]:
arr6 = np.array([10.2356,24.2456,0.45698],dtype=np.float64)
print(f"Array with data type as float:{arr6} ")

round_of = np.round(arr6, decimals=2)
print(f"Round of the array to two decimal: {round_of}")


Array with data type as float:[10.2356  24.2456   0.45698] 
Round of the array to two decimal: [10.24 24.25  0.46]


#### 9, create a 1D array with 5 elements, calculate the median


In [32]:
arr7 = np.arange(5)
print(f"Array with five element: {arr7}")
print(f"Median: {np.median(arr7)}")

Array with five element: [0 1 2 3 4]
Median: 2.0


#### 10, create a 1D array with 6 elements, calculate the median

In [33]:
arr8 = np.arange(10,16)
print(f"Array with five element: {arr8}")
print(f"Median: {np.median(arr8)}")

Array with five element: [10 11 12 13 14 15]
Median: 12.5


#### 11 create a 2D array 
  1. compute median along horizontal axis.
  2. compute median along vertical axis
  3. compute median of entire array

In [37]:
arr9 = np.arange(9).reshape(3,3)
print(f"2D Array: \n {arr9}")

# Compute median along horizontal axis
horizontal_axis = np.median(arr9,axis=1) 
print(f"Median along horizontal axis:{horizontal_axis}")

# Compute median along vertical axis
vertical_axis = np.median(arr9,axis=0) 
print(f"Median along vertical axis:{vertical_axis}")

# Median of entire array
median = np.median(arr9)
,print(f"Median of array: {median}")

2D Array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
Median along horizontal axis:[1. 4. 7.]
Median along vertical axis:[3. 4. 5.]
Median of array: 4.0


#### 12. Create a array with element as Student Marks, compute the mean of marks,

In [38]:
student_marks = np.array([87,78,74,82,91,60])
print(f"Mean of student marks: {np.mean(student_marks)}")

Mean of student marks: 78.66666666666667


####  13. create a 2D array 
  1. compute Mean along horizontal axis.
  2. compute Mean along vertical axis
  3. compute Mean of entire array

In [4]:
arr10 = np.arange(15).reshape(5,3)
print(f"2D Array: \n {arr10}")

# Compute mean along horizontal axis
horizontal_axis_mean = np.mean(arr10,axis=1) 
print(f"Mean along horizontal axis:{horizontal_axis_mean}")

# Compute mean along vertical axis
vertical_axis_mean = np.mean(arr10,axis=0) 
print(f"Mean along vertical axis:{vertical_axis_mean}")

# mean of entire array
mean = np.mean(arr10)
print(f"mean of array: {mean}")

2D Array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Mean along horizontal axis:[ 1.  4.  7. 10. 13.]
Mean along vertical axis:[6. 7. 8.]
mean of array: 7.0


#### 14. Create a array with element as Student Marks, compute the Standard Deviation of marks.

In [5]:
stud_marks = np.array([87,78,74,82,91,60])
print(f"Standard Deviation of student marks:{np.std(stud_marks)}")

Standard Deviation of student marks:10.027739304327548


### 15. create a 2D array 
   1. compute Standard Deviation along horizontal axis.
   2. compute Standard Deviation along vertical axis
   3. compute Standard Deviation of entire array

In [6]:
arr11 = np.arange(15).reshape(5,3)
print(f"2D Array: \n {arr11}")

# Compute std along horizontal axis
horizontal_axis_std = np.std(arr11,axis=1) 
print(f"STD along horizontal axis:{horizontal_axis_std}")

# Compute mean along vertical axis
vertical_axis_std = np.std(arr11,axis=0) 
print(f"STD along vertical axis:{vertical_axis_std}")

# mean of entire array
std = np.std(arr11)
print(f"STD of array: {std}")

2D Array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
STD along horizontal axis:[0.81649658 0.81649658 0.81649658 0.81649658 0.81649658]
STD along vertical axis:[4.24264069 4.24264069 4.24264069]
STD of array: 4.320493798938574


#### 16. Create an array and find minimum and maximum value of array 

In [7]:
arr12 = np.arange(15).reshape(5,3)
print(f"2D Array: \n {arr11}")
print(f"Maximum value of array: {np.max(arr12)}")
print(f"Minimum value of array: {np.min(arr12)}")

2D Array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
Maximum value of array: 14
Minimum value of array: 0
