In [1]:
# import necessary library
import numpy as np

### Q 1. Extract all odd numbers from array

In [4]:
def odd_element(array):
    mylist=[]
    for element in array:
        if element%2==1:
            mylist.append(element)
        convert_into_array = np.array(mylist)
    print('Data Type:',type(convert_into_array))
    print("Odd Element: ",convert_into_array)
        
        

In [5]:
odd_element([0,1,2,3,4,5,6,7,8,9])

Data Type: <class 'numpy.ndarray'>
Odd Element:  [1 3 5 7 9]


### Q 2. write a Numpy program to create a 3x3 matrix with values ranging 2 to 10

In [7]:
array1 = np.array([[2,3,4],[5,6,7],[8,9,10]])
print(array1)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [12]:
def Array():
    array = np.arange(2,11).reshape(3,3)
    return array
    

In [13]:
Array()

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

### Q3. Write a Numpy program to create a 3x4 matrix filled with values from 10 to 21 using conditional statement


In [24]:
import numpy as np

matrix = np.zeros((3, 4)) # Create a 3x4 zeros matrix

# Fill the matrix with values from 10 to 21 using a conditional statement
for i in range(3):
    for j in range(4):
        matrix[i, j] = 10 + i * 4 + j

print(matrix)


[[10. 11. 12. 13.]
 [14. 15. 16. 17.]
 [18. 19. 20. 21.]]


### Q 4.Write a numpy program to create a an array of all even integer from 30 to 70.
* Using Function
* Using Conditional statement

In [32]:
def even():
    mylist = []
    array = np.arange(30,71)
    for element in array:
        if element%2==0:
            mylist.append(element)
    print(np.array(mylist))
    
        

In [33]:
even()

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


#### Using Conditional Statement

In [37]:
mylist1 = []  # create empty list to store the array element
array4 = np.arange(30,71)
for i in array4:
    if i%2==0:
        mylist1.append(i)
print(f"Even Integers: {np.array(mylist1)}")

Even Integers: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


### Q 5.Write a numpy program to create two 3x3 Matrix and perform addition using function

In [57]:
matrix1 = np.arange(1,10).reshape(3,3)
print("First Matrix:\n",matrix1)

matrix2 = np.arange(101,110).reshape(3,3)
print("Second Matrix: \n",matrix2)

add = np.add(matrix1, matrix2)  # Addition using function
print(f"Addition of matrix using function:\n {add}")


First Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Second Matrix: 
 [[101 102 103]
 [104 105 106]
 [107 108 109]]
Addition of matrix using function:
 [[102 104 106]
 [108 110 112]
 [114 116 118]]


### Q 6. Extract all odd numbers, Even numbers from array

In [61]:
even_array = []
odd_array = []
array5 = np.arange(16)
print(f"Original Array: {array5}")
for element in array5:
    if element%2==0:
        even_array.append(element)
    else:
        odd_array.append(element)
print(f"Even element array: {even_array}")
print(f"Odd Element array: {odd_array}")
        



Original Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Even element array: [0, 2, 4, 6, 8, 10, 12, 14]
Odd Element array: [1, 3, 5, 7, 9, 11, 13, 15]
