### IMPORT NECESSARY LIBRARY

In [10]:
import numpy as np

# Q 1. Write a Numpy porgram to find the dot product of two arrays of different dimensions 

In [1]:
# Import the library numpy 
import numpy as np 

# Create the two array with different dimensions 
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([7,8,9])

# Dot product of two arrays 
product = np.dot(array1,array2)

# Display the result
print("First Array:")
print(array1)
print("Second Array:", array2)
print("Dot product of two array of different dimensions :", product)

First Array:
[[1 2 3]
 [4 5 6]]
Second Array: [7 8 9]
Dot product of two array of different dimensions : [ 50 122]


# Q 2. Write a Numpy porgram to create a 3x3 array with random values and subtract the mean of each row from each element 

In [8]:
# Import the library Numpy 
import numpy as np

# Create the 3x3 arrray with random values 
random_array = np.random.rand(3,3)

# Display the array
print(random_array)

#Calculate the mean of each row 
row_mean = np.mean(random_array, axis = 1 , keepdims= True)

# Subtraction the mean of each row from each element
result_array= np.subtract(row_mean, random_array)

# Display the result 
print("Mean of each row :")
print(row_mean)
print("Subtraction :")
print(result_array)

[[0.85197032 0.9028181  0.56647311]
 [0.83731562 0.76630492 0.23166484]
 [0.13853835 0.22346439 0.65342756]]
Mean of each row :
[[0.77375384]
 [0.61176179]
 [0.33847676]]
Subtraction :
[[-0.07821647 -0.12906426  0.20728073]
 [-0.22555383 -0.15454313  0.38009695]
 [ 0.19993842  0.11501238 -0.31495079]]


# Q 3. Write a Numpy program to create a 5x5 array with random values and replace the minimum value with 0.

In [12]:
# Import the library numpy 
import numpy as np 

# Create the 5x5 array with random values 
random_array = np.random.rand(5,5)

# Display the array 
print("Random Array :")
print(random_array)

#Find the minimum values 
min_value = np.min(random_array)

# Dislpay the minimum values 
print("Minimun values:", min_value)

# Replace the minimum value with 0
# Using the for loop
for i in range(5):
    for j in range(5):
        if random_array[i, j ]== min_value:
            random_array[i,j]=0
            
# Display the result
print("Replace the minmum valus with 0 :")
print(random_array)

Random Array :
[[0.79266565 0.52139344 0.61414906 0.50129774 0.03037045]
 [0.034066   0.87496245 0.76271316 0.17861621 0.35178689]
 [0.59269285 0.5383442  0.8032234  0.16101401 0.51597769]
 [0.12979399 0.91513984 0.79092355 0.04195913 0.38010666]
 [0.41373706 0.23594297 0.27842459 0.65272461 0.44629704]]
Minimun values: 0.030370448646427017
Replace the minmum valus with 0 :
[[0.79266565 0.52139344 0.61414906 0.50129774 0.        ]
 [0.034066   0.87496245 0.76271316 0.17861621 0.35178689]
 [0.59269285 0.5383442  0.8032234  0.16101401 0.51597769]
 [0.12979399 0.91513984 0.79092355 0.04195913 0.38010666]
 [0.41373706 0.23594297 0.27842459 0.65272461 0.44629704]]


In [13]:
# Import the library numpy 
import numpy as np 

# Create the 5x5 array with random values 
random_array = np.random.rand(5,5)

# Display the array 
print("Random Array :")
print(random_array)

#Find the minimum values 
min_value = np.min(random_array)

# Dislpay the minimum values 
print("Minimun values:", min_value)

# Replace the minimum value with 0
random_array[random_array == min_value]=0
            
# Display the result
print("Replace the minmum valus with 0 :")
print(random_array)

Random Array :
[[0.46099486 0.88546256 0.45100435 0.19321372 0.93942344]
 [0.32685317 0.52970919 0.55913316 0.11155585 0.04796022]
 [0.94073049 0.29761695 0.33750476 0.50045314 0.72724324]
 [0.35704569 0.88458973 0.3445261  0.51435986 0.21091235]
 [0.59481948 0.56190983 0.53370486 0.1512671  0.83831283]]
Minimun values: 0.04796021648334303
Replace the minmum valus with 0 :
[[0.46099486 0.88546256 0.45100435 0.19321372 0.93942344]
 [0.32685317 0.52970919 0.55913316 0.11155585 0.        ]
 [0.94073049 0.29761695 0.33750476 0.50045314 0.72724324]
 [0.35704569 0.88458973 0.3445261  0.51435986 0.21091235]
 [0.59481948 0.56190983 0.53370486 0.1512671  0.83831283]]


# Q 4. Write a Numpy program to repeat all the elements three times of a given array of string 

In [15]:
# Import the library numpy 
import numpy as np

# Create the array of string 
string_array = np.array(["Apple", "Banana", "Mango", "Orange"])

# Display the array 
print("Strig Array:")
print(string_array)

# Repeat all the elements three times of a given array of string
repeat_array = np.repeat(string_array,3)

#Display the repeat array
print("Repeat Array all elements three times :")
print(repeat_array)



Strig Array:
['Apple' 'Banana' 'Mango' 'Orange']
Repeat Array all elements three times :
['Apple' 'Apple' 'Apple' 'Banana' 'Banana' 'Banana' 'Mango' 'Mango'
 'Mango' 'Orange' 'Orange' 'Orange']


# Q 5. Write a NUmpy program to insert a space between character of all the elements of a given array.

In [21]:
# Import the library numpy 
import numpy as np 

# Create the array of string
array = np.array(["Apple", "Banana", "Mango", "Orange"])

# Display the array
print("Array :")
print(array)

# To insert a space between character of all elements of a given array
space_character_array = np.array([' '.join(list(word)) for word in array])

# Display the array 
print("A space between character of all elements of a given array:")
print(space_character_array)

Array :
['Apple' 'Banana' 'Mango' 'Orange']
A space between character of all elements of a given array:
['A p p l e' 'B a n a n a' 'M a n g o' 'O r a n g e']


# Q 6. Write a Numpy program to count the lowest index of "P" in a given array, element-wise.

    Original Array:
                    ['Python' 'PHP' 'JS''EXAMPLES' 'HTML']
                    
    count the lowest index of 'P':
                        [0 0 -1 4 -1]

In [25]:
# Import the library numpy 
import numpy as np

# Original array 
original_array = np.array(["Python", "PHP","JS","EXAMPLES","HTML"])

# Display the original array 
print("Original Array:", original_array)

# Count the lowest index of "P" in a given array 
lowest_index = np.char.find(original_array, 'P')

# Display the count the lowest index of "P"
print("Count the lowest index of P:", lowest_index)

Original Array: ['Python' 'PHP' 'JS' 'EXAMPLES' 'HTML']
Count the lowest index of P: [ 0  0 -1  4 -1]


# Q 7. Write a Numpy program to compute the mean, standard deviation and variance of a array 

In [31]:
# Import the library numpy 
import numpy as np

# Create the array 
array = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Display the array 
print("Array:")
print(array)

# Calculate the mean of given array
mean_array = np.mean(array)

# Display the mean of array
print("Mean of the array:", mean_array)

# Calculate the standard deviation of given array
std_array = np.std(array)

# Display the standard deviation of array ]
print("Standard Deviation of the array:", std_array)

# Calculate the variance of given array
variance_array = np.var(array)

# Display the variacne of array 
print("Variance of the array :",variance_array )

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean of the array: 5.0
Standard Deviation of the array: 2.581988897471611
Variance of the array : 6.666666666666667


# Q 8. Create a 1D array with values ranging from 0 to 9.

In [33]:
# Import the library numpy 
import numpy as np

# Create the 1D array 
array = np.arange(0,10)

# Display the array
print(array)

[0 1 2 3 4 5 6 7 8 9]


# Q 9.Extract all odd numbers from an array of 1-10.


In [1]:
arr = range(1, 11)
odds = [num for num in arr if num % 2 != 0]
print(odds) 

[1, 3, 5, 7, 9]


# Q 10.Calculate the sum of the diagonal elements of a 3x3 matrix.

In [2]:
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
sum_diagonal = matrix[0][0] + matrix[1][1] + matrix[2][2]
print(sum_diagonal)

15


# Q 11.Create a 3x3 identity matrix.

In [6]:
matrix = [[1 if i == j else 0 for j in range(3)] for i in range(3)]
matrix

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

# Q 12.Find the index of the maximum value in a 1 D array.

In [7]:
arr = [4, 7, 2, 9, 1]
max_value = max(arr)
max_index = arr.index(max_value)
print(max_index)

3


# Q 13.Count the number of occurrences of a specific value in an array,

In [8]:
arr = [3, 2, 4, 3, 5, 3]
value = 3
count = 0
for num in arr:
    if num == value:
        count += 1
print(count)

3


# Q 14. Replace all negative values in an array with 0

In [9]:
arr = [-1, 2, -3, 4, -5]
for i in range(len(arr)):
    if arr[i] < 0:
        arr[i] = 0
print(arr)

[0, 2, 0, 4, 0]


# Q 15.Create a random 2x2 matrix and compute its determinant

In [11]:
matrix = np.random.rand(2, 2)
determinant = np.linalg.det(matrix)
print(determinant)

0.07384032961317487


# Q 16.Calculate the square root of each element in a 1D array

In [12]:
arr = [9, 4, 16]
sqrt_arr = np.sqrt(arr)
print(sqrt_arr)

[3. 2. 4.]


# Q 17.Calculate the element-wise absolute values of an array

In [13]:
arr = [-1, -2, 3, 4]
absolute_values = [abs(num) for num in arr]
print(absolute_values)

[1, 2, 3, 4]


# Q 18.Compute the inverse of a 2x2 matrix

In [14]:
matrix = [[2, 1], [3, 1]]
inverse = np.linalg.inv(matrix)
print(inverse)

[[-1.  1.]
 [ 3. -2.]]


# Q 19. Find the correlation coefficient between two arrays

In [15]:
arr1 = [1, 2, 3, 4, 5]
arr2 = [2, 4, 5, 4, 3]
correlation = np.corrcoef(arr1, arr2)[0, 1]
print(correlation)

0.2773500981126146


# Q 20.Create a 1D array and remove all duplicate values

In [16]:
arr = [2, 1, 4, 3, 1, 5]
seen = set()
unique_values = []
for num in arr:
    if num not in seen:
        seen.add(num)
        unique_values.append(num)
print(arr)
print(unique_values)

[2, 1, 4, 3, 1, 5]
[2, 1, 4, 3, 5]


# Q 21.Create a 2D array and set all values above a certain threshold to that threshold, Threshold=0.5. (Create A random Array)

In [17]:
array_2d = np.random.rand(3, 4)
threshold = 0.5
array_2d[array_2d > threshold] = threshold
print(array_2d)

[[0.5        0.5        0.03394248 0.22427763]
 [0.5        0.5        0.5        0.46138058]
 [0.5        0.5        0.10513225 0.23828303]]


# Q 22.Create a 1 D array and set the values between 10 and 20 to 0

In [18]:
array_1d = np.random.randint(0, 30, 10)
array_1d[(array_1d >= 10) & (array_1d <= 20)] = 0
print(array_1d)

[ 4  6  2  0 23 22  9 25  0  8]


# Q 23.Create a 1 D array and append a new element to the end.

In [20]:
arr = np.arange(10)
new_arr = np.append(arr, 42)
print(new_arr)

[ 0  1  2  3  4  5  6  7  8  9 42]


# Q 24.Calculate the element-wise absolute difference between two arrays

In [21]:
array_a = np.random.rand(5)
array_b = np.random.rand(5)
abs_diff = np.abs(array_a - array_b)
print(abs_diff)

[0.54229745 0.87723695 0.32058754 0.45857516 0.41838744]


# Q 25.Convert the elements of a 1 D array to strings

In [22]:
string_array = new_arr.astype(str)
print(string_array)

['0' '1' '2' '3' '4' '5' '6' '7' '8' '9' '42']


# Q 26.Check if all elements in a 1 D array are non-zero

In [23]:
are_non_zero = np.all(new_arr != 0)
print(are_non_zero)

False


# Q 27.Calculate the pairwise Euclidean distance between two arrays.


In [27]:
array_b = np.random.rand(3) 
array_c = np.random.rand(3)
euclidean_distance = np.linalg.norm(array_b - array_c)
print(euclidean_distance)

0.4970524056819988


# Q 28.Create an 1D array and set the values between the 25th and 75th percentile T0 0.


In [28]:
array_1d_percentile = np.random.rand(20)
percentile_25, percentile_75 = np.percentile(array_1d_percentile, [25, 75])
array_1d_percentile[(array_1d_percentile >= percentile_25) & (array_1d_percentile <= percentile_75)] = 0
print(array_1d_percentile)

[0.56594634 0.         0.85975543 0.         0.         0.
 0.         0.12170384 0.04448271 0.         0.         0.07749581
 0.         0.         0.96820383 0.02974669 0.98689612 0.
 0.89423553 0.04288587]


--------------------------------------------------------------------------------------------- THANK YOU -----------------------------------------------------------------------------------