## **Packages**


In [1]:
import numpy as np

**Note: Unlike lists, arrays can only store data of a similar type.**



# **Create Array Using Python List**

In [ ]:
# create a list named list1
list1 = [2, 4, 6, 8]

In [ ]:
# create numpy array using list1
array = np.array(list1)

In [ ]:
print(array)

[2 4 6 8]


**Create an Array Using np.zeros()**


In [ ]:
# create an array with 4 elements filled with zeros
array = np.zeros(4)
print(array)

[0. 0. 0. 0.]


**Create an Array With np.arange()**

In [ ]:
# create an array with values from 0 to 6
array = np.arange(7)
print(array)

[0 1 2 3 4 5 6]


In [ ]:
# Create an array that starts from the integer 1, ends at 20,incremented by 3
array = np.arange(1, 20, 3)
print(array)

[ 1  4  7 10 13 16 19]


In [ ]:
c = np.arange(1, 20, 3, dtype=int)
print(c)

[ 1  4  7 10 13 16 19]


In [ ]:
c = np.arange(1, 20, 3, dtype=float)
print(c)

[ 1.  4.  7. 10. 13. 16. 19.]


**Create an Empty NumPy Array**


In [ ]:
empty_arr = np.empty(4)
print(empty_arr)

[1.e-323 2.e-323 3.e-323 4.e-323]


Note:---The empty array is actually not empty, it has some values in it.

It is because although we are creating an empty array, NumPy will try to add some value to it. The values stored in the array are arbitrary and have no significance

# **Create a 2-D NumPy Array**

In [ ]:
# create a 2D array with 2 rows and 4 columns
array1 = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8]])

In [ ]:
print(array1)

[[1 2 3 4]
 [5 6 7 8]]


**Create N-D Array with a Specified Value**

In [ ]:
# Create a 2-D array with elements initialized to 5
numpy_array = np.full((2, 2), 5)

print("Array:", numpy_array)

Array: [[5 5]
 [5 5]]


**Create Empty N-D NumPy Array**

In [ ]:
# create an empty 2D array with 2 rows and 2 columns
array1 = np.empty((2, 2))

print("2-D Array: ")
print(array1)

# create an empty 3D array of shape (2, 2, 2)
array2 = np.empty((2, 2, 2))

print("\n3-D Array: ")
print(array2)

2-D Array: 
[[1.e-323 2.e-323]
 [3.e-323 4.e-323]]

3-D Array: 
[[[4.637837e-310 0.000000e+000]
  [0.000000e+000 0.000000e+000]]

 [[0.000000e+000 0.000000e+000]
  [0.000000e+000 0.000000e+000]]]


# Create a 3-D NumPy Array

In [ ]:
# create a 3D array with 2 "slices", each of 3 rows and 4 columns
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])

In [ ]:
print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


# **NumPy Data Types**
To check the data type of a NumPy array, we can use the dtype attribute

In [ ]:
# create an array of  integers
int_array = np.array([-3, -1, 0, 1])

# create an array of floating-point numbers
float_array = np.array([0.1, 0.2, 0.3])

# create an array of complex numbers
complex_array = np.array([1+2j, 2+3j, 3+4j])

# check the data type of int_array
print(int_array.dtype)

# check the data type of float_array
print(float_array.dtype)

# check the data type of complex_array
print(complex_array.dtype)

int64
float64
complex128


# **Finding size, shape and dimension**

In [ ]:
array1.ndim

3

In [ ]:
array1.shape

(2, 3, 4)

In [ ]:
array1.size

24

In [ ]:
def l_vowels(user_s):
    vowels = 'aeiou'
    count = 0
    for char in user_s:
           if char in vowels:
            count += 1
    return count

string = input("Enter a string: ")
res = l_vowels(string)
print(res)

Enter a string: hello
2


In [ ]:
def p_even_num():
    while True:
        num = int(input("Enter a number: "))
        if num == 95:
            break
        if num % 2 == 0:
            print(num)
p_even_num()

Enter a number: 95


In [30]:
arr = np.chararray((5), itemsize=2, unicode=True)
arr[:] = 'abc'
arr

chararray(['ab', 'ab', 'ab', 'ab', 'ab'], dtype='<U2')

In [25]:
arr = np.array('ab')
arr = np.chararray(arr.shape, itemsize=7)
arr

chararray('', dtype='<U7')

In [31]:
np.random.rand(3,4)

array([[0.01278133, 0.91978702, 0.04598853, 0.57450275],
       [0.55646294, 0.20013755, 0.607486  , 0.55266992],
       [0.33621964, 0.52806069, 0.20780277, 0.69572639]])

In [6]:
arr = np.repeat((5,2),5)
arr[:] = 3
arr

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [7]:
arr = np.array(range(10))
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [9]:
array = np.array(range(1,6))
print(array)
flip = np.flip(array)
print("Flip Array: ",flip)

# 2D array
array1 = np.arange(12).reshape(4,3)
print("Orginal Array: \n",array1)
print("Flip 2D Array: \n",np.flip(array1))

[1 2 3 4 5]
Flip Array:  [5 4 3 2 1]
Orginal Array: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Flip 2D Array: 
 [[11 10  9]
 [ 8  7  6]
 [ 5  4  3]
 [ 2  1  0]]


In [11]:
# Find mean and max form the array
array2 = np.arange(12).reshape(4,3)
print(f"Maximun no of array: {np.max(array2)}")
print(f"Minimum no of array: {np.min(array2)}")

Maximun no of array: 11
Minimum no of array: 0


In [13]:
# Multiply each element with specific no
array3 = np.arange(12).reshape(4,3)
print(array3)

print("Multiply each element with specific no:",array3*2)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
Multiply each element with specific no: [[ 0  2  4]
 [ 6  8 10]
 [12 14 16]
 [18 20 22]]


In [14]:
array4 = np.arange(12)
reshape = np.reshape(array4,(4,3))
print(reshape)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [10]:
# Declare  2D array with 10 element and display the element which are > 5
array5 = np.arange(10)
print(array5)
#print(array5 >= 5)


# more = array5*(array5>=5)
# print(more[more!=0])


# print(array5[array5>5])

[0 1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True  True]


In [34]:
# Create 1 D array and display the even no from array
arr = np.arange(15)
for i in arr:
    if i%2==0:
        print(i)

0
2
4
6
8
10
12
14


In [35]:
# Create 1 D array and display the even no from array
arr = np.arange(15)
mylist = []
for i in arr:
    if i%2==0:
        mylist.append(i)
print(np.array(mylist))

[ 0  2  4  6  8 10 12 14]


In [37]:
arr[arr%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [45]:
arr1 = np.array([1,145,11,8,91,100])
even = arr1[arr1 %2!=1]
even

array([  8, 100])

In [46]:
# Find index location
np.where(even)

(array([0, 1], dtype=int64),)

In [17]:
arr = np.array(range(6))

print(arr)
print(np.where(arr[arr%2==0]))

[0 1 2 3 4 5]
(array([1, 2], dtype=int64),)


In [58]:
x = np.array(range(12)).reshape(3,4)
x[1,2]

6

In [ ]:
np.char.add()