# Numpy

**Numpy VS List**

In [2]:
# Create a list with different element
mylist = [2,4,6,8]
print(mylist)

[2, 4, 6, 8]


In [6]:
# try to multiply 2.5 directly to the created list
mylist * 2.2

TypeError: can't multiply sequence by non-int of type 'str'

**Lists cannot operate over the entire data together. You need to run map or apply functions to multiply each element with 2.2. Let's try to perform this using a NumPy array**

In [7]:
# Import numpy
import numpy as np

In [8]:
array = np.array([1,3,5,7])
print(array)

[1 3 5 7]


In [9]:
# Multiply element with 2.5
array * 2.5

array([ 2.5,  7.5, 12.5, 17.5])

In [10]:
# Create a 1-D array using with the elements (1, abc, True)
myarray = np.array([1,'abc',True])
myarray

array(['1', 'abc', 'True'], dtype='<U11')

## Operations over Arrays

In [11]:
list1 = [10,20,30]
list2 = [100,200,300]

# Add two list using + operator
list3 = list1+ list2
list3

[10, 20, 30, 100, 200, 300]

In [12]:
array1 = np.array([10,20,30])
array2 = np.array([100,200,300])

# Additon of two array
array1+array2

array([110, 220, 330])

## Create Array Using Python List

In [13]:
# create a list named list1
list1 = [1,3,5,7]

# Creating array
array1 = np.array(list1)
array1

array([1, 3, 5, 7])

## Create an Array Using np.zeros()

In [14]:
array = np.zeros(5)
array

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((3,3), dtype='int', order='F')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Create an Array With np.arange()

In [16]:
# create an array with values from 0 to 6
array = np.arange(7)
array

array([0, 1, 2, 3, 4, 5, 6])

In [17]:
# Create an array that starts from the integer 1, ends at 20,incremented by 3
array = np.arange(1,21,3)
array

array([ 1,  4,  7, 10, 13, 16, 19])

In [18]:
c = np.arange(1, 20, 3, dtype=int)
print(c)

[ 1  4  7 10 13 16 19]


In [19]:
c = np.arange(1, 20, 3, dtype=float)
print(c)

[ 1.  4.  7. 10. 13. 16. 19.]


In [15]:
np.arange(1,18,2, dtype='float')

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17.])

## Create an Empty NumPy Array

In [27]:
empty_arr = np.empty(4)
empty_arr

array([ 2.5,  7.5, 12.5, 17.5])

In [19]:
np.empty(5)

array([6.23042070e-307, 4.67296746e-307, 1.69121096e-306, 2.37666896e-312,
       6.95211151e-310])

**Note:---The empty array is actually not empty, it has some values in it.**

## Create a 2-D NumPy Array

In [28]:
# create a 2D array with 2 rows and 4 columns
array1 = np.array([[5,10,15,20],
                  [6,12,18,24]])
array1

array([[ 5, 10, 15, 20],
       [ 6, 12, 18, 24]])

## Create N-D Array with a Specified Value

In [31]:
arr = np.full((3,3),2)
arr

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

## Create Empty N-D NumPy Array

In [33]:
# create an empty 2D array with 2 rows and 2 columns
arr1 = np.empty((2,2))
print(f"2D Array {arr1}")

# create an empty 3D array of shape (2, 2, 2)
arr2 = np.empty((2,2,2))
print(f"\n 3D Array {arr2}")


2D Array [[ 2.5  7.5]
 [12.5 17.5]]

 3D Array [[[6.23042070e-307 4.67296746e-307]
  [1.69121096e-306 6.23058707e-307]]

 [[2.22526399e-307 6.23053614e-307]
  [7.56592338e-307 9.34588061e-307]]]


## Create a 3-D NumPy Array

In [34]:
# create a 3D array with 2 "slices", each of 3 rows and 4 columns
array1 = np.array([[[0, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 11, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 17, 19, 20],
                 [21, 22, 23, 24]]])

array1

array([[[ 0,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 11, 11, 12]],

       [[13, 14, 15, 16],
        [17, 17, 19, 20],
        [21, 22, 23, 24]]])

## NumPy Data Types

In [36]:
# create an array of  integers
int_array = np.array([3, -2, 0, 1])

# create an array of floating-point numbers
float_array = np.array([0.7, 0.2, 0.3])

# create an array of complex numbers
complex_array = np.array([5+2j, 2+3j, 3+4j])

# check the data type of int_array
print(int_array.dtype)

# check the data type of float_array
print(float_array.dtype)

# check the data type of complex_array
print(complex_array.dtype)

int32
float64
complex128


### Numpy Function

In [1]:
import numpy as np

### np.eye()---------Create Diagonal Matrix
- np.eye(5)  # Using single element 
- np.eye(3,5) # First element for row and second element for column

In [20]:
array = np.eye(2,3)
array

array([[1., 0., 0.],
       [0., 1., 0.]])

In [6]:
arr = np.eye(5,10)
arr

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

### np.diag() #Create a indentity matrix

In [11]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1)

diag = np.diag(arr1)
print(f"Digonal element of array is:{diag}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Digonal element of array is:[1 5 9]


### np.indices([3,3]) -------- First parameter for dimension and second element for indices

* np.indices() will create a set of arrays which are stacked as 1-D array. is set of array is one per dimension with each representing variation of the dimension

In [20]:
arr2 = np.indices([4,2])
arr2

array([[[0, 0],
        [1, 1],
        [2, 2],
        [3, 3]],

       [[0, 1],
        [0, 1],
        [0, 1],
        [0, 1]]])