In [ ]:
""" 1. Create Array Using Python List. [2, 4, 6, 8]

2. Create An Array by Directly Passing element

3. Create an array with 4 elements filled with zeros

4. Create an array filled with values 1

5. Create an array with values from 0 to 4.

6. Create an array with values from 1 to 8 with a step of 27. Generate an array of 5 random numbers.

7. Generate an array of 5 random numbers.

8. Create an empty array of length 4.

9. Create a 2D array with 2 rows and 4 columns

10. Create a 3D array with 2 "slices", each of 3 rows and 4 columns (also use Type() function)

11. Create a 2-D array with elements initialized to 5

12. create an array of integers, floating Points, Complex Number.

13. create an array of integers. convert data type of int_array to float.

14. create a 2-D array

    1. check the dimension of array
    2. return total number of elements in array
    3. return a tuple that gives size of array in each dimension
    4. check the data type of array
    5. Check memory address of array

15. Create array of element [1, 3, 5, 7, 9)
    1. Access 1 ^ e * 3 ^ (e') * 0.5 ^ e element
    2. Change the value of 1 deg element as 12 and 3 ^ * element as 14
    3. Access Last element, Second-Last Element
    4. Modify Last element, Second-Last Element

16. Create 2-D array [ [1, 3, 5, 7], [9, 11, 13, 15], [2, 4, 6, 8l]
    1. access the element at the second row and fourth column
    2. access the element at the first row and second column"""

In [2]:
import numpy as np

In [3]:
#  1. Create Array Using Python List. [2, 4, 6, 8]
list1 = [2,4,6,8]
array = np.array(list1)
print(f"Array Using Python List: {array}")

Array Using Python List: [2 4 6 8]


In [4]:
# 2. Create An Array by Directly Passing element
arr = np.array([2,4,6,8,10])
print(f"Array: {arr}")

Array: [ 2  4  6  8 10]


In [5]:
# 3. Create an array with 4 elements filled with zeros
zero_array = np.zeros(4)
print(f"Array with all zeros: {zero_array}")

Array with all zeros: [0. 0. 0. 0.]


In [6]:
# 4. Create an array filled with values 1
ones_array = np.ones(4)
print(f"Array with all ones: {ones_array}")

Array with all ones: [1. 1. 1. 1.]


In [7]:
# 5. Create an array with values from 0 to 4.
array1 = np.arange(0,4)
print(f"Array with 0 to 4 values: {array1}")

Array with 0 to 4 values: [0 1 2 3]


In [10]:
# 6. Create an array with values from 1 to 8 with a step of 27. 
array2 = np.arange(1,8,2)
print(f"Random Array: {array2}")

Random Array: [1 3 5 7]


In [11]:
# Generate an array of 5 random numbers.
random = np.random.random(5)
print(f"Random Array: {random}")

Random Array: [0.83125027 0.97073346 0.17211946 0.21165776 0.10501334]


In [12]:
# 8. Create an empty array of length 4.
empty = np.empty(4)
print(f"Empty array with shape:{empty}")

Empty array with shape:[1. 1. 1. 1.]


In [13]:
# 9. Create a 2D array with 2 rows and 4 columns
array2d = np.array([[1,2,3,4],[5,6,7,8]])
print(array2d)

[[1 2 3 4]
 [5 6 7 8]]


In [35]:
# 10. Create a 3D array with 2 "slices", each of 3 rows and 4 columns (also use Type() function)
array3d_with_two_slices = np.zeros((2,3,4),int)
print(f"Type: {type(array3d_with_two_slices)}")
array3d_with_two_slices


Type: <class 'numpy.ndarray'>


array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [33]:
#  11. Create a 2-D array with elements initialized to 5
array_2d = np.ones((3,3),int)
print(f"2D Array with all element 5: \n{array_2d*5}")
print(f"Dimenesion of array: {array_2d.ndim}")

2D Array with all element 5: 
[[5 5 5]
 [5 5 5]
 [5 5 5]]
Dimenesion of array: 2


In [37]:
# 12. create an array of integers, floating Points, Complex Number
intarr = np.ones(5, int)
print(f"Array Fill with all integer values: {intarr}")

floatarr = np.ones(5)
print(f"Array fill with all float values: {floatarr}")

complexarr = np.ones(5,complex)
print(f"Array fill with all complex vales: {complexarr}")

Array Fill with all integer values: [1 1 1 1 1]
Array fill with all float values: [1. 1. 1. 1. 1.]
Array fill with all complex vales: [1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]


In [39]:
#  13. create an array of integers. convert data type of int_array to float.
arrint = np.arange(1,10, dtype=float)
arrint

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [54]:
# 14. create a 2-D array
array3 = np.arange(6).reshape(2,3)
print(f"2D array: \n{array3}")

#  1. check the dimension of array
print(f"Dimension of array:{array3.ndim}")

#   2. return total number of elements in array
print(f"Length of the array: {array3.size}")

#   3. return a tuple that gives size of array in each dimension
print(f"Shape of the array: {array.shape}")

#   4. check the data type of array
print(f"Data type of arryay: {type(array3)}")

#   5. Check memory address of array
print(f"Memory address of array: {id(array)}")


2D array: 
[[0 1 2]
 [3 4 5]]
Dimension of array:2
Length of the array: 6
Shape of the array: (4,)
Data type of arryay: <class 'numpy.ndarray'>
Memory address of array: 1390421981296


In [58]:
# 15. Create array of element [1, 3, 5, 7, 9]
array4 = np.array([1, 3, 5, 7, 9])
print(array4)

#   1. Access first, third and 5th element
print(f"Accessing the First element: {array4[0]}, Accessing the third element: {array4[2]} , Accessing the fifth element: {array4[4]}")

#   2. Change the value of 1 element as 12 and 3 element as 14
array4[0], array4[2] = 12, 14
print(array4)

#  3. Access Last element, Second-Last Element
print(f"Access last element: {array[-1]} Second last element: {array4[-2]}")

#  4. Modify Last element, Second-Last Element
array4[-1], array4[-2] = 1, 2
print(f"Modify Last element, Second-Last Element: {array4}")

[1 3 5 7 9]
Accessing the First element: 1, Accessing the third element: 5 , Accessing the fifth element: 9
[12  3 14  7  9]
Access last element: 8 Second last element: 7
Modify Last element, Second-Last Element: [12  3 14  2  1]


In [65]:
# 16. Create 2-D array 
array5 = np.array([ [1, 3, 5, 7], [9, 11, 13, 15], [2, 4, 6, 8]])
print(f"2D array: \n {array5}")

#   1. access the element at the second row and fourth column
print(f"Access the element at the second row and fourth column: {array5[1][3]}")

#   2. access the element at the first row and second column
print(f"Access the element at the first row and second column: {array5[0][1]}")

2D array: 
 [[ 1  3  5  7]
 [ 9 11 13 15]
 [ 2  4  6  8]]
Access the element at the second row and fourth column: 15
Access the element at the first row and second column: 3
